export * from './base'
export { academicYearRepository } from './academicYear'
export { departmentRepository } from './department'
export { facultyRepository } from './faculty'
export { subjectRepository } from './subject'
export { sectionRepository } from './section'
export { roomRepository } from './room'
export { timeSlotRepository } from './timeSlot'
export { timetableEntryRepository } from './timetableEntry'
export { attendanceRepository } from './attendance'
export { substitutionRuleRepository } from './substitutionRule'
export { substitutionRunRepository, substitutionAssignmentRepository } from './substitutionRun'
export { settingsRepository } from './settings'